#!/usr/bin/env python3
"""Import the pinned Gorilla OEM STEP references as centered local SI OBJ meshes.

Requires optional numpy and OCP; performs no download, mass assignment, axis/drive
selection, topology repair, or license approval. All derivatives stay in ignored
artifacts. Existing files are protected unless --overwrite is explicitly passed.

Historical cached OBJs were generated by the ignored import_oem_step_meshes.py,
SHA256 f99fc95a383bf5e3c59297db91185454882acfa6f948a8752030256bcd46f1a3.
Archiving this portable source does not reissue those existing conversion records.
Only a real future conversion run may assign this entry's SHA to new outputs.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = ROOT / "artifacts/gorilla_v0_1/internal_module_sources"
SOURCE_HASHES = {
    "cubemars_ak80_64": "dabe73fd22a27ed922bea0971b39ea8fd74de31cf45c495bee96945c63fc68ea",
    "victron_ng_25_6v100ah": "ae0fc44a4acdb6d0369787c3aca0436ff68e880ba4e80f2d8b531a6ca3da7f35",
}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def record_path(path):
    try:
        return str(Path(path).relative_to(ROOT))
    except ValueError:
        return str(path)


def arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SOURCE / "imported_geometry")
    parser.add_argument("--ak80-step", type=Path, help="Override the pinned AK80-64 STEP input path")
    parser.add_argument("--victron-step", type=Path, help="Override the pinned Victron STEP input path")
    parser.add_argument("--asset", choices=("all", *SOURCE_HASHES), default="all")
    parser.add_argument("--overwrite", action="store_true", help="Explicitly replace cached geometry and conversion records")
    args = parser.parse_args()
    args.source_dir, args.output_dir = args.source_dir.resolve(), args.output_dir.resolve()
    if not args.output_dir.is_relative_to((ROOT / "artifacts").resolve()):
        parser.error("OEM derivatives must remain under this repository's ignored artifacts directory")
    return args


def convert(args):
    try:
        import OCP  # Optional dependency, imported only for actual conversion.
        import numpy
    except ImportError as exc:
        raise SystemExit("Actual conversion requires Python with numpy and OCP installed; nothing is downloaded or installed automatically.") from exc
    SOURCE, OUT = args.source_dir, args.output_dir
    from collections import Counter
    import zipfile
    import numpy as np
    import OCP
    from OCP.STEPControl import STEPControl_Reader
    from OCP.IFSelect import IFSelect_RetDone
    from OCP.TColStd import TColStd_SequenceOfAsciiString
    from OCP.TopAbs import TopAbs_FACE,TopAbs_SOLID,TopAbs_REVERSED
    from OCP.TopExp import TopExp,TopExp_Explorer
    from OCP.TopTools import TopTools_IndexedMapOfShape
    from OCP.TopoDS import TopoDS
    from OCP.TopLoc import TopLoc_Location
    from OCP.BRep import BRep_Tool
    from OCP.BRepMesh import BRepMesh_IncrementalMesh
    from OCP.BRepCheck import BRepCheck_Analyzer
    from OCP.BRepBndLib import BRepBndLib
    from OCP.Bnd import Bnd_Box
    source_manifest=json.loads((SOURCE/'source_manifest.json').read_text()) if (SOURCE/'source_manifest.json').exists() else []
    entries=[('cubemars_ak80_64',args.ak80_step or SOURCE/'cubemars/ak80-64.stp'),('victron_ng_25_6v100ah',args.victron_step or SOURCE/'victron_ng_25_6v100ah.step')]
    entries=[(name,path.resolve()) for name,path in entries if args.asset in ('all',name)]
    for name,path in entries:
     if sha(path)!=SOURCE_HASHES[name]:raise ValueError('Unexpected OEM source version: '+str(path))
    for name,path in entries:
     for suffix in ('_local_m.obj','_import_manifest.json'):
      target=OUT/(name+suffix)
      if target.exists() and not args.overwrite:raise FileExistsError('Preserve existing conversion evidence; choose another --output-dir or explicitly --overwrite: '+str(target))
    if (OUT/'import_manifest.json').exists() and not args.overwrite:raise FileExistsError('Existing aggregate import manifest; refusing to reissue cached geometry without --overwrite')
    OUT.mkdir(parents=True,exist_ok=True)
    results=[]
    for name,path in entries:
     print('IMPORT',name,flush=True)
     raw=path.read_text(errors='replace');hash_before=sha(path)
     reader=STEPControl_Reader();status=reader.ReadFile(str(path));assert status==IFSelect_RetDone,(name,status)
     lu,au,su=(TColStd_SequenceOfAsciiString() for _ in range(3));reader.FileUnits(lu,au,su)
     names=lambda q:[q.Value(i).ToCString() for i in range(1,q.Length()+1)]
     file_units={'length':names(lu),'angle':names(au),'solid_angle':names(su)}
     assert file_units['length'] and all('milli' in u.lower() for u in file_units['length']),file_units
     # OCCT's system-unit numeric convention is millimetres per output unit.
     reader.SetSystemLengthUnit(1.0);assert abs(reader.SystemLengthUnit()-1)<1e-12
     transferred=reader.TransferRoots();assert transferred>0
     shape=reader.OneShape();assert not shape.IsNull()
     valid=bool(BRepCheck_Analyzer(shape,True).IsValid())
     if not valid:raise ValueError('Invalid OEM CAD BRep: '+name)
     bb=Bnd_Box();BRepBndLib.AddOptimal_s(shape,bb,False,False);bounds_cad=np.array(bb.Get()).reshape(2,3)
     face_map=TopTools_IndexedMapOfShape();solid_map=TopTools_IndexedMapOfShape();TopExp.MapShapes_s(shape,TopAbs_FACE,face_map);TopExp.MapShapes_s(shape,TopAbs_SOLID,solid_map)
     owners={};shared=[]
     for sid in range(1,solid_map.Extent()+1):
      exp=TopExp_Explorer(solid_map.FindKey(sid),TopAbs_FACE)
      while exp.More():
       fid=face_map.FindIndex(exp.Current())
       if fid in owners and owners[fid]!=sid:shared.append(fid)
       owners.setdefault(fid,sid);exp.Next()
     tess=BRepMesh_IncrementalMesh(shape,.15,False,.20,True);assert tess.IsDone()
     vertices=[];triangles=[];tri_owner=[];lookup={};missing=[];degenerate=0
     # Welding only within CAD solid identity preserves separate contacting parts.
     # 10nm in metres is 1e-5mm. OBJ does not merge distinct OEM solids.
     weld_mm=1e-5
     for fid in range(1,face_map.Extent()+1):
      face=TopoDS.Face_s(face_map.FindKey(fid));loc=TopLoc_Location();poly=BRep_Tool.Triangulation_s(face,loc)
      if poly is None or poly.NbTriangles()==0:missing.append(fid);continue
      tr=loc.Transformation();sid=owners.get(fid,0);ids={}
      for i in range(1,poly.NbNodes()+1):
       p=poly.Node(i).Transformed(tr);xyz=np.array([p.X(),p.Y(),p.Z()]);key=(sid,*np.rint(xyz/weld_mm).astype(np.int64).tolist())
       if key not in lookup:lookup[key]=len(vertices);vertices.append(xyz)
       ids[i]=lookup[key]
      reverse=(face.Orientation()==TopAbs_REVERSED)^tr.IsNegative()
      for i in range(1,poly.NbTriangles()+1):
       t=list(poly.Triangle(i).Get());t=[ids[j] for j in t]
       if reverse:t[1],t[2]=t[2],t[1]
       a,b,c=(vertices[j] for j in t)
       if len(set(t))!=3 or np.linalg.norm(np.cross(b-a,c-a))<=1e-12:degenerate+=1;continue
       triangles.append(t);tri_owner.append(sid)
     if missing:raise ValueError('Unmeshed source CAD faces: '+str(missing))
     v=np.asarray(vertices,float);t=np.asarray(triangles,int);assert len(v)>0 and len(t)>0 and np.isfinite(v).all()
     # Remove unused vertices after degenerate-face rejection, still per-solid.
     used=np.unique(t);remap=np.full(len(v),-1,int);remap[used]=np.arange(len(used));v=v[used];t=remap[t]
     lo,hi=v.min(0),v.max(0);center=(lo+hi)/2;local=(v-center)*.001
     assert np.max(np.abs(local.min(0)+local.max(0)))<1e-12
     obj=OUT/(name+'_local_m.obj')
     with obj.open('w') as f:
      f.write('# OEM STEP-derived spatial display mesh. SI metres; AABB-centered; original axes retained.\n')
      f.write('# No mass, collision/strength, actuator selection or licence permission is inferred.\n')
      for p in local:f.write('v '+' '.join(f'{x:.12f}' for x in p)+'\n')
      current=None
      for tri,sid in zip(t,tri_owner):
       if sid!=current:f.write(f'g cad_solid_{sid:04d}\n');current=sid
       f.write('f '+' '.join(str(int(i)+1) for i in tri)+'\n')
     # Read the written OBJ, ensuring the delivered rather than in-memory mesh.
     rverts=[];rtri=[]
     for line in obj.read_text().splitlines():
      if line.startswith('v '):rverts.append(list(map(float,line.split()[1:])))
      elif line.startswith('f '):rtri.append([int(q)-1 for q in line.split()[1:]])
     rv=np.asarray(rverts);rt=np.asarray(rtri);assert rv.shape==local.shape and rt.shape==t.shape and np.array_equal(rt,t)
     area=np.linalg.norm(np.cross(rv[rt[:,1]]-rv[rt[:,0]],rv[rt[:,2]]-rv[rt[:,0]]),axis=1)/2
     assert np.isfinite(rv).all() and np.all(area>1e-18) and rt.min()>=0 and rt.max()<len(rv)
     components=[]
     for sid in sorted(set(tri_owner)):
      tt=rt[np.array(tri_owner)==sid];edge=Counter();directed=Counter()
      for a,b,c in tt:
       for aa,bb in ((a,b),(b,c),(c,a)):edge[tuple(sorted((int(aa),int(bb))))]+=1;directed[int(aa),int(bb)]+=1
      components.append({'cad_solid_id':sid,'triangle_count':len(tt),'boundary_edge_count':sum(n==1 for n in edge.values()),'nonmanifold_edge_count':sum(n>2 for n in edge.values()),'inconsistent_two_face_edge_winding_count':sum(n==2 and (directed[a,b]!=1 or directed[b,a]!=1) for (a,b),n in edge.items())})
     manifest_source=next((q for q in source_manifest if q.get('file')==path.name),None)
     if manifest_source:assert manifest_source['sha256']==hash_before
     transform=np.eye(4);transform[:3,:3]*=.001;transform[:3,3]=-center*.001
     report={'robot_id':'gorilla_v0_1','asset_id':name,'source_path':record_path(path),'conversion_script_sha256':sha(Path(__file__)),'source_sha256':hash_before,'source_manifest_entry':manifest_source,'source_unchanged_after_import':sha(path)==hash_before,'source_length_unit_header':'SI_UNIT(.MILLI.,.METRE.)','step_file_units':file_units,'occt_version':OCP.__version__,'occt_target_unit_mm_per_coordinate':reader.SystemLengthUnit(),'transferred_roots':transferred,'cad_face_count':face_map.Extent(),'cad_solid_count':solid_map.Extent(),'cad_brep_valid':valid,'cad_bounds_mm':bounds_cad.tolist(),'cad_dimensions_mm':np.ptp(bounds_cad,axis=0).tolist(),'tessellation':{'linear_deflection_mm':.15,'linear_deflection_m':.00015,'angular_deflection_rad':.20,'relative':False,'all_face_TopLoc_transforms_applied':True,'reversed_and_reflected_faces_winding_adjusted':True,'weld_tolerance_mm':weld_mm,'weld_scope':'CAD solid identity; touching separate solids retained'},'mesh_before_center_bounds_mm':[lo.tolist(),hi.tolist()],'source_center_mm':center.tolist(),'source_mm_to_obj_local_m_4x4':transform.tolist(),'rotation':'identity: preserve STEP assembly axes','mesh_vertices':len(rv),'mesh_triangles':len(rt),'minimum_triangle_area_m2':float(area.min()),'obj_path':record_path(obj),'obj_sha256':sha(obj),'obj_bounds_local_m':[rv.min(0).tolist(),rv.max(0).tolist()],'obj_dimensions_xyz_m':np.ptp(rv,axis=0).tolist(),'mesh_nonempty_finite_indices_and_nonzero_triangles_verified':True,'unmeshed_cad_faces':missing,'rejected_degenerate_triangles':degenerate,'face_ownership_conflicts':sorted(set(shared)),'mesh_component_topology':components,'mesh_closed_manifold_by_component':all(q['boundary_edge_count']==0 and q['nonmanifold_edge_count']==0 and q['inconsistent_two_face_edge_winding_count']==0 for q in components),'status':'imported_spatial_reference_candidate_only','mass_from_volume':False,'licence_status':'OEM derived display mesh only in ignored artifacts; redistribution permission not established','not_validated':['mass/inertia/material','actuation/drive architecture or mounting position','manufacturing fit or collision tolerance','reuse/redistribution licence']}
     if name=='cubemars_ak80_64':
      archive=SOURCE/'cubemars/ak80_64_vendor_cad.zip'
      if archive.exists():
       with zipfile.ZipFile(archive) as z:members=[q for q in z.namelist() if q.lower().endswith(('.step','.stp'))];matches=[q for q in members if hashlib.sha256(z.read(q)).hexdigest()==hash_before]
       report['vendor_archive']={'path':record_path(archive),'sha256':sha(archive),'exact_extracted_step_matching_members':matches}
     (OUT/(name+'_import_manifest.json')).write_text(json.dumps(report,indent=2));results.append(report)
     print(json.dumps({'asset':name,'cad_valid':valid,'faces':face_map.Extent(),'solid_count':solid_map.Extent(),'vertices':len(rv),'triangles':len(rt),'dimensions_m':report['obj_dimensions_xyz_m'],'bounds_m':report['obj_bounds_local_m'],'missing_faces':missing,'mesh_manifold_by_component':report['mesh_closed_manifold_by_component']},indent=2),flush=True)
    (OUT/'import_manifest.json').write_text(json.dumps({'robot_id':'gorilla_v0_1','units':'metre','axis_convention':'OEM STEP axes retained; no Gorilla placement selected','conversion_script_sha256':sha(Path(__file__)),'assets':[{'asset_id':q['asset_id'],'obj_path':q['obj_path'],'obj_sha256':q['obj_sha256'],'source_sha256':q['source_sha256'],'manifest_path':record_path(OUT/(q['asset_id']+'_import_manifest.json')),'dimensions_xyz_m':q['obj_dimensions_xyz_m'],'bounds_local_m':q['obj_bounds_local_m'],'cad_brep_valid':q['cad_brep_valid'],'mesh_closed_manifold_by_component':q['mesh_closed_manifold_by_component']} for q in results]},indent=2))


if __name__ == "__main__":
    convert(arguments())
