"""Check a wheel's exact resource inventory using its freshly installed Python."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tomllib
import zipfile

import mujoco
import sai_agent
from sai_agent.paths import resource_root, model_root
from sai_agent.godot_controller import GodotController
from sai_agent.cargo_godot import CargoGodotController
from sai_agent.cargo_task import CargoTask
from sai_agent.legacy_crawl import CrawlTransport


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--wheel', type=Path, required=True)
    args = parser.parse_args()
    checkout = Path(__file__).resolve().parents[2]
    package = Path(sai_agent.__file__).resolve().parent
    root = resource_root()
    assert root == package / 'bundle', 'Run this with the installed wheel, not editable source'
    assert package != checkout / 'src/sai_agent'
    assert model_root() == model_root('Sai_Agent_001')

    config = tomllib.loads((checkout / 'pyproject.toml').read_text())
    includes = config['tool']['hatch']['build']['targets']['wheel']['force-include']
    tracked = subprocess.check_output(
        ['git', '-C', str(checkout), 'ls-files', '-z'], text=True,
    ).split('\0')
    expected = {}
    for source, target in includes.items():
        for path in tracked:
            if path == source or path.startswith(source + '/'):
                expected[target + path[len(source):]] = checkout / path
    assert expected, 'No tracked runtime resources found'
    expected_modules = {path.removeprefix('src/') for path in tracked
                        if path.startswith('src/sai_agent/') and path.endswith('.py')}
    with zipfile.ZipFile(args.wheel) as wheel:
        names = {name for name in wheel.namelist() if not name.endswith('/')}
        bundled = {name for name in names if name.startswith('sai_agent/bundle/')}
        assert bundled == set(expected), (
            f'Missing resources: {sorted(set(expected) - bundled)}; '
            f'Unexpected resources: {sorted(bundled - set(expected))}'
        )
        modules = {name for name in names if name.startswith('sai_agent/')
                   and not name.startswith('sai_agent/bundle/') and name.endswith('.py')}
        assert modules == expected_modules, 'Wheel Python module inventory differs from checkout'
        for name in names:
            if name in expected:
                source = expected[name]
            elif name.startswith('sai_agent/'):
                source = checkout / 'src' / name
            else:
                continue  # Wheel metadata is generated by the build backend.
            data = wheel.read(name)
            assert data == source.read_bytes(), f'Wheel differs from checkout: {name}'
            installed = package.parent / name
            assert installed.read_bytes() == data, f'Installed resource differs: {name}'
        print(f'Exact tracked resource inventory and hashes passed ({len(names)} wheel entries)')

    for robot_id, actuators in [('Sai_Agent_001', 23), ('Sai_Agent_002', 22)]:
        models = model_root(robot_id)
        for xml in ['full/robot.xml', 'full/visual.xml', 'locomotion.xml']:
            model = mujoco.MjModel.from_xml_path(str(models / xml))
            assert model.nu == (16 if xml == 'locomotion.xml' else actuators)
        assert GodotController(root, robot_id=robot_id).model.nu == actuators
        for name in ['ascent60', 'descent60']:
            profile = root / 'shared/policies/experimental' / f'{name}.json'
            metadata = json.loads(profile.read_text())
            actor = profile.parent / metadata['actor']
            assert hashlib.sha256(actor.read_bytes()).hexdigest() == metadata['onnx_sha256']
            GodotController(root, stair_profile=profile, robot_id=robot_id)
        CargoTask(model_dir=models / 'full')
        CargoGodotController(model_dir=models / 'full')
        print(f'{robot_id}: installed models, default/experimental policies and cargo passed')
    CrawlTransport()
    goose = model_root('Goose_V0.1')
    historical = mujoco.MjModel.from_xml_path(str(goose / 'full/robot.xml'))
    assert historical.nu == 16, 'Preserved RC2 actuator count changed'
    from sai_agent.goose.stage_one import StageOneEnv
    checkpoint = StageOneEnv(
        goose / 'training_checkpoint/robot.xml',
        root / 'robots/Goose_V0.1/configs/training_checkpoint_contract.json',
        num_envs=1, randomize=False, commands=False, auto_reset=False,
    )
    assert checkpoint.models[0].nu == 18
    assert checkpoint.observations().shape == (1, 65)
    print('Goose_V0.1: installed historical model and current 65/18 checkpoint passed (loading only)')
    print('Installed distribution checks passed')


if __name__ == '__main__':
    main()
